# Generated by Django 5.0.3 on 2024-03-24 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppGed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='remarque',
            field=models.CharField(default='', max_length=1024),
        ),
    ]
