# Generated by Django 5.0.3 on 2024-03-24 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppGed', '0003_alter_document_extention_alter_document_remarque'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='piecejointe',
            field=models.FileField(default=1, upload_to='public'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='extention',
            field=models.CharField(choices=[('pdf', 'Fichier Pdf'), ('docx', 'Document Word'), ('xlsx', 'Tableau Excel'), ('txt', 'Fichier Plat'), ('html', 'Lien Internet')], default='pdf', max_length=5),
        ),
    ]
