# Generated by Django 5.0.3 on 2024-03-24 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppGed', '0004_document_piecejointe_alter_document_extention'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='chemin_document',
        ),
        migrations.AlterField(
            model_name='document',
            name='piecejointe',
            field=models.FileField(upload_to='public', verbose_name='Fichier'),
        ),
    ]
