# Generated by Django 5.0.3 on 2024-06-14 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppGed', '0006_alter_document_categorie_alter_document_extention_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='extention',
        ),
    ]
